<?php include __DIR__.'/../header.phtml'; ?>

<h1> Tchat I@D Digital </h1>
<h2>Identifiez vous !</h2>
<form method="POST" action="/public/?controller=security&action=loginCheck">
    <div>
        <label for="login">Login</label>
        <input type="text" name="login" id="login">
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password">
    </div>
    <div>
        <button type="submit">Se connecter</button>
    </div>
</form>

<?php include __DIR__.'/../footer.phtml'; ?>

